config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :contacts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :relationship, presence: true

  validates :name, :user_id, presence: true

  enum relationship: { personal: 'personal', professional: 'professional' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts, dependent: :destroy

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      user_path(resource)
    else
      super
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:new_contact) do |u|
      u.permit(:name, :relationship)
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1 or /contacts/1.json
  def show
    @contact = current_user.contacts.find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.user = current_user
  end

  # GET /contacts/1/edit
  def edit
    @contact
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :relationship, :email, :phone, :city, :state, :country)
    end

    def authenticate_user!
      unless current_user == @contact.user
        redirect_to root_url, alert: "You must be logged in to access this page.", status: :forbidden
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/registrations_controller.rb
class RegistrationController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  def new
    super
  end

  def create
    super
  end

  def update
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show ]

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome #{@user.name}!"
      redirect_to @user
    else
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end

    def authenticate_user!
      redirect_to new_user_session_path unless current_user == @user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact_card.html.erb
<div class="row justify-content-md-center">
    <div class="col-6">
      <div class="card shadow mb-5 bg-white rounded">
        <div class="card-header">
          <h3 class="card-title text-center">
            <%= @contact.name %>
          </h3>
        </div>
        <div class="card-body pr-2">
          <p class="card-text pr-2 mb-3"> 
            <ul class="list-group list-group-flush">
              <li class="list-group-item"> Email: <%= @contact.email %> </li>
              <li class="list-group-item"> Phone: <%= @contact.phone %> </li>
              <li class="list-group-item"> City: <%= @contact.city %> </li>
              <li class="list-group-item"> State: <%= @contact.state %> </li>
              <li class="list-group-item"> Country: <%= @contact.country %> </li>
              <li class="list-group-item"> Relationship: <%= @contact.relationship %> </li>
            </ul>
          </p>
          <div class="row">
            <div class="d-grid gap-2 col-12 mx-auto">
              <%= link_to "Edit contact", edit_contact_path(@contact.id), class:"btn btn-primary" %>
              <%= link_to "Delete contact", contact_path(@contact.id), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-primary" %>
              <%= link_to 'Back', contacts_path, class:"btn" %>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>

app/views/contacts/_form.html.erb
<div class="container-fluid">
  <%= form_with(model: contact, local: true) do |form| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row justify-content-md-center">
      <div class="col-6">
        <div class="card shadow mb-5 bg-white rounded mt-3">
          <div class="card-header text-center">
            <h2> Create Contact </h2>
          </div>
          <div class="card-body justify-content-md-center">
            <div class="mb-3">
              <%= form.label :name, class:"form-label" %><br />
              <%= form.text_field :name, autofocus: true, autocomplete: "name", class:"form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :email, class:"form-label" %><br />
              <%= form.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :phone, class:"form-label" %> <br />
              <%= form.text_field :phone, autofocus: true, autocomplete: "tel", class:"form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :city, class:"form-label" %> <br/>
              <%= form.text_field :city, autofocus: true, autocomplete: "city", class:"form-control" %>
            </div>

            <div class="mb-3">
            <%= form.label :state, class:"form-label" %> <br/>
              <%= form.text_field :state, autofocus: true, autocomplete: "state", class:"form-control" %>
            </div>

            <div class="mb-3">
            <%= form.label :country, class:"form-label" %> <br/>
              <%= form.text_field :country, autofocus: true, autocomplete: "country", class:"form-control" %>
            </div>

            <div class="mb-3 form-check">
              <%= form.label :relationship, class:"form-check-label mt-3", style:"font-size: 20px;" %> <br/>
              <%= form.radio_button :relationship, 'personal', class:"form-check-input", type:"radio", :checked => true %> Personal
            </div>
            
            <div class="mb-3 form-check">
              <%= form.radio_button :relationship, 'professional', class:"form-check-input", type:"radio" %> Professional
            </div>

            <div class="actions">
              <%= form.submit "Create/Update", class:"btn btn-primary col-12" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Contacts</h1>

<div class="container">
  <% if current_user.present? %>
    <% @contacts.each do |contact| %>
        <div class="row justify-content-md-center">
          <div class="col-6">
            <div class="card shadow mb-5 bg-white rounded">
              <div class="card-header">
                <h3 class="card-title text-center">
                  <%= contact.name %>
                </h3>
              </div>
              <div class="card-body pr-2">
                <p class="card-text pr-2 mb-3"> 
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"> Email: <%= contact.email %> </li>
                    <li class="list-group-item"> Phone: <%= contact.phone %> </li>
                    <li class="list-group-item"> City: <%= contact.city %> </li>
                    <li class="list-group-item"> State: <%= contact.state %> </li>
                    <li class="list-group-item"> Country: <%= contact.country %> </li>
                    <li class="list-group-item"> Relationship: <%= contact.relationship %> </li>
                  </ul>
                </p>
                <div class="row">
                  <div class="d-grid gap-2 col-8 mx-auto">
                    <%= link_to "Edit contact", edit_contact_path(contact.id), class:"btn btn-primary" %>
                    <%= link_to "Delete contact", contact_path(contact.id), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-primary" %>
                  </div>
                </div>
              </div>
              
            </div>
          </div>
        </div>
    <% end %>
  <% end %>
</div>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="container mt-3">
  <%= render 'contact_card'%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand">
  <div class="container-fluid">
    <% if !user_signed_in? %>
      <%= link_to "Home", root_path, class: "navbar-brand p-2", id: "logo"%>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "User", user_path(current_user), class:"nav-link"%>
        
        </li>
          <li class="nav-item">
            <li >
              <%= link_to "Create new contact", new_contact_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Contacts", contacts_path, class: "nav-link" %>
            </li>
              <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FractalAgenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
     <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render 'layouts/navbar'%>
    <div id="page-content"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
  <div class='container-fluid' id="home-container">
    <div class="jumbotron text-center text-white p-3" id="home-jumbo">
      <h1 class="display-4"> Test Agenda </h1>
      <p class="lead">Sign up to start saving your contacts!</p>
      <hr class="my-4">
      <p> Only the user can view its contacts </p>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class='card shadow rounded pt-4 mt-3' style="width: 30em;">
      <div class="card-header">
        <h3 class="card-title text-center">
          User
        </h3>
      </div>
      <div class='card-body'>
        <h5 class='card-title'>
          Name: <%= @current_user.name %>
        </h5>
        <p class='card-text'>
          Email: <%= @current_user.email %>
        </p>
        <div class="col-12 justify-content-md-center">
        <%= link_to "Create new contact", new_contact_path, class:"btn btn-primary pr-3", style:"width: 65%" %>
        <% if @current_user.contacts.present? %> 
          <%= link_to "Contacts", contacts_path, class:"btn btn-primary pr-4", style:"width: 33%;" %>
        <% end %>
        </div>
        <div class="row mt-3 justify-content-md-center">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-outline-primary", style:"width: 95%;"%>
        </div>
      </div>
    </div>
  </div>
  <br/>
</div>


           

        